export type PropertySeedItem = {
  name: string;
  category: string;
  location: string;
  nightlyPrice: string;
  guests: number;
  facilities: string[];
  contactEmail: string;
  websiteUrl?: string;
  instagramHandle?: string;
  images: string[];
  description?: string;
  featured: boolean;
  pickMonth: number;
  pickYear: number;
};

export const SEED_PROPERTIES: PropertySeedItem[] = [
  // November 2025
  {
    name: "Minmore Farm",
    category: "Farmstay",
    location: "Glenlivet, Perthshire",
    nightlyPrice: "105.00",
    guests: 8,
    facilities: ["Highland farm", "Whisky country", "Log cabin", "Wild walks", "Stargazing"],
    contactEmail: "stay@minmorefarm.co.uk",
    websiteUrl: "https://minmorefarm.co.uk",
    instagramHandle: "@minmorefarm",
    images: ["/images/properties/farmstay_1_5.jpg", "/images/properties/farmstay_1_1.jpg", "/images/properties/farmstay_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  {
    name: "Treetops Perthshire",
    category: "Unique Stay",
    location: "Perthshire, Scotland",
    nightlyPrice: "310.00",
    guests: 4,
    facilities: ["Elevated cabin", "Loch access", "Log stove", "Wild swimming"],
    contactEmail: "hello@treetopsperthshire.co.uk",
    websiteUrl: "https://treetopsperthshire.co.uk",
    instagramHandle: "@treetopsperthshire",
    images: ["/images/properties/unique_1_5.jpg", "/images/properties/unique_1_1.jpg", "/images/properties/unique_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  {
    name: "Howgill Lodge",
    category: "Cabin/hut",
    location: "Sedbergh, Yorkshire Dales",
    nightlyPrice: "175.00",
    guests: 6,
    facilities: ["Off-grid lodge", "Fell views", "Sauna", "Star gazing", "Hot tub"],
    contactEmail: "stay@howgilllodge.co.uk",
    websiteUrl: "https://howgilllodge.co.uk",
    instagramHandle: "@howgilllodge",
    images: ["/images/properties/cabin_1_5.jpg", "/images/properties/cabin_1_1.jpg", "/images/properties/cabin_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  {
    name: "Dittisham Mill Creek",
    category: "Cottage",
    location: "Dartmouth, Devon",
    nightlyPrice: "160.00",
    guests: 8,
    facilities: ["Estuary cottage", "Boat mooring", "Crab catching", "Log fire", "Dogs"],
    contactEmail: "stay@dittishammillcreek.co.uk",
    websiteUrl: "https://dittishammillcreek.co.uk",
    instagramHandle: "@dittishammillcreek",
    images: ["/images/properties/cottage_1_5.jpg", "/images/properties/cottage_1_1.jpg", "/images/properties/cottage_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  {
    name: "The Punch Bowl Inn",
    category: "Pub with Rooms",
    location: "Crosthwaite, Cumbria",
    nightlyPrice: "140.00",
    guests: 16,
    facilities: ["Michelin Bib", "Lake views", "Log fires", "Dog-friendly", "Real ales"],
    contactEmail: "info@thepunchbowl.co.uk",
    websiteUrl: "https://thepunchbowl.co.uk",
    instagramHandle: "@punchbowlinn",
    images: ["/images/properties/pub_1_5.jpg", "/images/properties/pub_1_1.jpg", "/images/properties/pub_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  {
    name: "Estelle Manor",
    category: "Estate/Manor",
    location: "Eynsham, Oxfordshire",
    nightlyPrice: "290.00",
    guests: 108,
    facilities: ["3,000-acre estate", "Roman spa", "108 rooms", "4 restaurants", "Pool"],
    contactEmail: "reservations@estellemanor.com",
    websiteUrl: "https://estellemanor.com",
    instagramHandle: "@estellemanor",
    images: ["/images/properties/estate_1_5.jpg", "/images/properties/estate_1_1.jpg", "/images/properties/estate_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  {
    name: "Cornish Tipi Holidays",
    category: "Pick of the Month",
    location: "St Kew, Cornwall",
    nightlyPrice: "150.00",
    guests: 50,
    facilities: ["Tipi village", "Wild swimming", "Woodland", "Solar power", "Community"],
    contactEmail: "enquiries@cornishtipis.co.uk",
    websiteUrl: "https://cornishtipis.co.uk",
    instagramHandle: "@cornishtipis",
    images: ["/images/properties/pick_1_5.jpg", "/images/properties/pick_1_1.jpg", "/images/properties/pick_1_2.jpg"],
    featured: false,
    pickMonth: 11,
    pickYear: 2025,
  },
  // December 2025
  {
    name: "Glebe House",
    category: "Farmstay",
    location: "Hunstanton, Norfolk",
    nightlyPrice: "115.00",
    guests: 12,
    facilities: ["Working farm", "Coastal walks", "Farmhouse B&B", "Log fires", "Dogs"],
    contactEmail: "stay@glebehousefarm.co.uk",
    websiteUrl: "https://glebehousefarm.co.uk",
    instagramHandle: "@glebehousefarm",
    images: ["/images/properties/farmstay_1_1.jpg", "/images/properties/farmstay_1_2.jpg", "/images/properties/farmstay_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  {
    name: "Nymet Treehouses",
    category: "Unique Stay",
    location: "North Devon",
    nightlyPrice: "250.00",
    guests: 4,
    facilities: ["Scandi-style treehouses", "Opening balconies", "Hot tubs", "Award winning"],
    contactEmail: "stay@nymettreehouses.co.uk",
    websiteUrl: "https://nymettreehouses.co.uk",
    instagramHandle: "@nymettreehouses",
    images: ["/images/properties/unique_1_1.jpg", "/images/properties/unique_1_2.jpg", "/images/properties/unique_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  {
    name: "Winter Wonderhut",
    category: "Cabin/hut",
    location: "Carlisle, Cumbria",
    nightlyPrice: "120.00",
    guests: 2,
    facilities: ["Winter shepherd hut", "Frost views", "Wood burner", "Stargazing"],
    contactEmail: "stay@longriggfarm.co.uk",
    websiteUrl: "https://longriggfarm.co.uk",
    instagramHandle: "@longriggfarm",
    images: ["/images/properties/cabin_1_1.jpg", "/images/properties/cabin_1_2.jpg", "/images/properties/cabin_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  {
    name: "Kerswell Farm",
    category: "Cottage",
    location: "Cullompton, Devon",
    nightlyPrice: "105.00",
    guests: 8,
    facilities: ["Farmhouse cottage", "Orchard", "Log fire", "Dogs", "Countryside quiet"],
    contactEmail: "info@kerswellfarm.co.uk",
    websiteUrl: "https://kerswellfarm.co.uk",
    instagramHandle: "@kerswellfarm",
    images: ["/images/properties/cottage_1_1.jpg", "/images/properties/cottage_1_2.jpg", "/images/properties/cottage_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  {
    name: "The Feathers Woodstock",
    category: "Pub with Rooms",
    location: "Woodstock, Oxfordshire",
    nightlyPrice: "165.00",
    guests: 30,
    facilities: ["Historic inn", "Log fires", "Blenheim Palace nearby", "Fine dining"],
    contactEmail: "enquiries@feathers.co.uk",
    websiteUrl: "https://feathers.co.uk",
    instagramHandle: "@featherswoodstock",
    images: ["/images/properties/pub_1_1.jpg", "/images/properties/pub_1_2.jpg", "/images/properties/pub_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  {
    name: "Cowley Manor",
    category: "Estate/Manor",
    location: "Cowley, Cotswolds",
    nightlyPrice: "295.00",
    guests: 36,
    facilities: ["55-acre estate", "C-Side Spa", "Pools", "Lakes", "Restaurant", "Art"],
    contactEmail: "info@cowleymanorexperimental.com",
    websiteUrl: "https://cowleymanorexperimental.com",
    instagramHandle: "@cowleymanorexperimental",
    images: ["/images/properties/estate_1_1.jpg", "/images/properties/estate_1_2.jpg", "/images/properties/estate_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  {
    name: "The Pig at Bridge Place",
    category: "Pick of the Month",
    location: "Canterbury, Kent",
    nightlyPrice: "195.00",
    guests: 40,
    facilities: ["Kitchen garden hotel", "Spa treatments", "Potting shed", "Log fires"],
    contactEmail: "reservations@thepighotel.com",
    websiteUrl: "https://thepighotel.com",
    instagramHandle: "@the_pig_hotels",
    images: ["/images/properties/pick_1_1.jpg", "/images/properties/pick_1_2.jpg", "/images/properties/pick_1_3.jpg"],
    featured: false,
    pickMonth: 12,
    pickYear: 2025,
  },
  // January 2026
  {
    name: "East Trenean Farm",
    category: "Farmstay",
    location: "Looe, Cornwall",
    nightlyPrice: "115.00",
    guests: 10,
    facilities: ["Luxury farm barns", "Hot tub", "Coast views", "Walking", "Dog-friendly"],
    contactEmail: "stay@easttrenean.co.uk",
    websiteUrl: "https://easttrenean.co.uk",
    instagramHandle: "@easttreneanfarm",
    images: ["/images/properties/farmstay_1_2.jpg", "/images/properties/farmstay_1_3.jpg", "/images/properties/farmstay_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  {
    name: "Tall Ship Houseboat",
    category: "Unique Stay",
    location: "Oban, Highlands",
    nightlyPrice: "204.00",
    guests: 6,
    facilities: ["Historic tall ship", "Loch views", "3 bedrooms", "Unique experience", "Tranquil"],
    contactEmail: "info@tallshiphouseboat.co.uk",
    websiteUrl: "https://tallshiphouseboat.co.uk",
    instagramHandle: "@tallshiphouseboat",
    images: ["/images/properties/unique_1_2.jpg", "/images/properties/unique_1_3.jpg", "/images/properties/unique_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  {
    name: "Longshed Cabin",
    category: "Cabin/hut",
    location: "Keswick, Cumbria",
    nightlyPrice: "165.00",
    guests: 4,
    facilities: ["Mountain cabin", "Sauna", "Wild swimming", "Stargazing", "Off-grid"],
    contactEmail: "stay@longshed.co.uk",
    websiteUrl: "https://longshed.co.uk",
    instagramHandle: "@longshedkeswick",
    images: ["/images/properties/cabin_1_2.jpg", "/images/properties/cabin_1_3.jpg", "/images/properties/cabin_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  {
    name: "Hillside Cottage",
    category: "Cottage",
    location: "Ambleside, Lake District",
    nightlyPrice: "140.00",
    guests: 6,
    facilities: ["Lakeside village", "Log fire", "Hot tub", "Fell walking", "Cosy"],
    contactEmail: "stay@hillsidecottage.co.uk",
    websiteUrl: "https://hillsidecottage.co.uk",
    instagramHandle: "@hillsidecottagelakes",
    images: ["/images/properties/cottage_1_2.jpg", "/images/properties/cottage_1_3.jpg", "/images/properties/cottage_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  {
    name: "The Torridon Inn",
    category: "Pub with Rooms",
    location: "Torridon, Highlands",
    nightlyPrice: "145.00",
    guests: 20,
    facilities: ["Mountain inn", "Wild landscape", "Real ales", "Guided walks", "Views"],
    contactEmail: "info@thetorridon.com",
    websiteUrl: "https://thetorridon.com",
    instagramHandle: "@thetorridoninn",
    images: ["/images/properties/pub_1_2.jpg", "/images/properties/pub_1_3.jpg", "/images/properties/pub_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  {
    name: "Coworth Park",
    category: "Estate/Manor",
    location: "Ascot, Berkshire",
    nightlyPrice: "295.00",
    guests: 70,
    facilities: ["Georgian manor", "240 acres", "Equestrian", "Spa", "Michelin dining", "Polo"],
    contactEmail: "reservations@coworthpark.com",
    websiteUrl: "https://coworthpark.com",
    instagramHandle: "@coworthpark",
    images: ["/images/properties/estate_1_2.jpg", "/images/properties/estate_1_3.jpg", "/images/properties/estate_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  {
    name: "The Wellbeing Farm",
    category: "Pick of the Month",
    location: "Bolton, Lancashire",
    nightlyPrice: "160.00",
    guests: 90,
    facilities: ["Quirky barn", "Yoga", "Seasonal food", "Dance", "Workshops", "Laughter"],
    contactEmail: "hello@thewellbeingfarm.co.uk",
    websiteUrl: "https://thewellbeingfarm.co.uk",
    instagramHandle: "@thewellbeingfarm",
    images: ["/images/properties/pick_1_2.jpg", "/images/properties/pick_1_3.jpg", "/images/properties/pick_1_4.jpg"],
    featured: false,
    pickMonth: 1,
    pickYear: 2026,
  },
  // February 2026
  {
    name: "Rucksack Farm",
    category: "Farmstay",
    location: "Snowdonia, Wales",
    nightlyPrice: "110.00",
    guests: 6,
    facilities: ["Working hill farm", "Eco cabin", "Views of Snowdon", "Yoga", "Wild walks"],
    contactEmail: "stay@rucksackfarm.co.uk",
    websiteUrl: "https://rucksackfarm.co.uk",
    instagramHandle: "@rucksackfarm",
    images: ["/images/properties/farmstay_1_3.jpg", "/images/properties/farmstay_1_4.jpg", "/images/properties/farmstay_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  {
    name: "The Ark Houseboat",
    category: "Unique Stay",
    location: "York, Yorkshire",
    nightlyPrice: "175.00",
    guests: 8,
    facilities: ["River houseboat", "Hot tub", "Riverside restaurant", "Glamping", "York"],
    contactEmail: "stay@thearkboat.co.uk",
    websiteUrl: "https://thearkboat.co.uk",
    instagramHandle: "@thearkboat",
    images: ["/images/properties/unique_1_3.jpg", "/images/properties/unique_1_4.jpg", "/images/properties/unique_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  {
    name: "Inshriach Bothy",
    category: "Cabin/hut",
    location: "Aviemore, Cairngorms",
    nightlyPrice: "75.00",
    guests: 4,
    facilities: ["Remote bothy", "Snow views", "Red squirrels", "Whisky", "Wild"],
    contactEmail: "hello@inshriachhouse.co.uk",
    websiteUrl: "https://inshriachhouse.co.uk",
    instagramHandle: "@inshriachhouse",
    images: ["/images/properties/cabin_1_3.jpg", "/images/properties/cabin_1_4.jpg", "/images/properties/cabin_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  {
    name: "Plas Cadnant",
    category: "Cottage",
    location: "Menai Bridge, Anglesey",
    nightlyPrice: "145.00",
    guests: 6,
    facilities: ["Walled garden estate", "Cottage", "Sea views", "Walking", "History"],
    contactEmail: "info@plascadnant.co.uk",
    websiteUrl: "https://plascadnant.co.uk",
    instagramHandle: "@plascadnant",
    images: ["/images/properties/cottage_1_3.jpg", "/images/properties/cottage_1_4.jpg", "/images/properties/cottage_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  {
    name: "The Pheasant",
    category: "Pub with Rooms",
    location: "Helmsley, Yorkshire",
    nightlyPrice: "130.00",
    guests: 20,
    facilities: ["Country inn", "Moors views", "Local ales", "Seasonal menu", "Dogs"],
    contactEmail: "reception@thepheasantinn.co.uk",
    websiteUrl: "https://thepheasantinn.co.uk",
    instagramHandle: "@thepheasantinnhelmsley",
    images: ["/images/properties/pub_1_3.jpg", "/images/properties/pub_1_4.jpg", "/images/properties/pub_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  {
    name: "Whatley Manor",
    category: "Estate/Manor",
    location: "Malmesbury, Wiltshire",
    nightlyPrice: "295.00",
    guests: 23,
    facilities: ["Cotswolds manor", "Le Mazot spa", "Michelin dining", "Pool", "Gardens"],
    contactEmail: "enquiries@whatleymanor.com",
    websiteUrl: "https://whatleymanor.com",
    instagramHandle: "@whatleymanor",
    images: ["/images/properties/estate_1_3.jpg", "/images/properties/estate_1_4.jpg", "/images/properties/estate_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  {
    name: "Skibo Castle",
    category: "Pick of the Month",
    location: "Dornoch, Highlands",
    nightlyPrice: "450.00",
    guests: 23,
    facilities: ["Historic castle", "Golf", "Spa", "Farm", "Falconry", "Exclusive members"],
    contactEmail: "reservations@carnegieclub.co.uk",
    websiteUrl: "https://carnegieclub.co.uk",
    instagramHandle: "@carnegieclub",
    images: ["/images/properties/pick_1_3.jpg", "/images/properties/pick_1_4.jpg", "/images/properties/pick_1_5.jpg"],
    featured: false,
    pickMonth: 2,
    pickYear: 2026,
  },
  // March 2026
  {
    name: "Fforest Farm",
    category: "Farmstay",
    location: "Cardigan, Wales",
    nightlyPrice: "125.00",
    guests: 20,
    facilities: ["Rewilding farm", "Sauna", "Fire", "River swimming", "Forest", "Community"],
    contactEmail: "hello@coldatnight.co.uk",
    websiteUrl: "https://coldatnight.co.uk",
    instagramHandle: "@fforest_farm",
    images: ["/images/properties/farmstay_1_4.jpg", "/images/properties/farmstay_1_5.jpg", "/images/properties/farmstay_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
  {
    name: "Canopy in the Trees",
    category: "Unique Stay",
    location: "Shrewsbury, Shropshire",
    nightlyPrice: "190.00",
    guests: 4,
    facilities: ["Forest treehouses", "Hot tubs", "Rope bridges", "Dog-friendly", "Sauna"],
    contactEmail: "hello@canopyinthetrees.co.uk",
    websiteUrl: "https://canopyinthetrees.co.uk",
    instagramHandle: "@canopyinthetrees",
    images: ["/images/properties/unique_1_4.jpg", "/images/properties/unique_1_5.jpg", "/images/properties/unique_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
  {
    name: "Brownscombe Spring",
    category: "Cabin/hut",
    location: "Colyton, Devon",
    nightlyPrice: "130.00",
    guests: 4,
    facilities: ["Shepherd huts", "Spring wildflower meadow", "Hot tubs", "Dogs"],
    contactEmail: "hello@brownscomberetreat.co.uk",
    websiteUrl: "https://brownscomberetreat.co.uk",
    instagramHandle: "@brownscomberetreat",
    images: ["/images/properties/cabin_1_4.jpg", "/images/properties/cabin_1_5.jpg", "/images/properties/cabin_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
  {
    name: "Trehane Estate",
    category: "Cottage",
    location: "Probus, Cornwall",
    nightlyPrice: "125.00",
    guests: 6,
    facilities: ["Camellia gardens", "Cottage", "Log fire", "Dog-friendly", "Walking"],
    contactEmail: "stay@trehaneestate.co.uk",
    websiteUrl: "https://trehaneestate.co.uk",
    instagramHandle: "@trehaneestate",
    images: ["/images/properties/cottage_1_4.jpg", "/images/properties/cottage_1_5.jpg", "/images/properties/cottage_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
  {
    name: "The Arundell Arms",
    category: "Pub with Rooms",
    location: "Lifton, Devon",
    nightlyPrice: "140.00",
    guests: 25,
    facilities: ["Fishing hotel", "Fly fishing", "Country inn", "Seasonal food", "Quiet"],
    contactEmail: "reservations@arundellarms.com",
    websiteUrl: "https://arundellarms.com",
    instagramHandle: "@arundellarms",
    images: ["/images/properties/pub_1_4.jpg", "/images/properties/pub_1_5.jpg", "/images/properties/pub_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
  {
    name: "Gravetye Manor",
    category: "Estate/Manor",
    location: "West Hoathly, Sussex",
    nightlyPrice: "285.00",
    guests: 17,
    facilities: ["Elizabethan manor", "Walled garden", "Michelin dining", "Pool", "Spa"],
    contactEmail: "info@gravetyemanor.co.uk",
    websiteUrl: "https://gravetyemanor.co.uk",
    instagramHandle: "@gravetyemanor",
    images: ["/images/properties/estate_1_4.jpg", "/images/properties/estate_1_5.jpg", "/images/properties/estate_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
  {
    name: "St Enodoc Hotel",
    category: "Pick of the Month",
    location: "Rock, Cornwall",
    nightlyPrice: "240.00",
    guests: 20,
    facilities: ["Coastal boutique", "Estuary views", "Restaurant", "Spa", "Golf nearby"],
    contactEmail: "reservations@enodoc-hotel.co.uk",
    websiteUrl: "https://enodoc-hotel.co.uk",
    instagramHandle: "@stenodochotel",
    images: ["/images/properties/pick_1_4.jpg", "/images/properties/pick_1_5.jpg", "/images/properties/pick_1_1.jpg"],
    featured: false,
    pickMonth: 3,
    pickYear: 2026,
  },
];
